/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as NewsRouteImport } from './routes/news'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstituencyRouteImport } from './routes/constituency'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstituencyRoute = ConstituencyRouteImport.update({
  id: '/constituency',
  path: '/constituency',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/complaints': typeof ComplaintsRoute
  '/constituency': typeof ConstituencyRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/news': typeof NewsRoute
  '/schemes': typeof SchemesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/complaints': typeof ComplaintsRoute
  '/constituency': typeof ConstituencyRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/news': typeof NewsRoute
  '/schemes': typeof SchemesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/complaints': typeof ComplaintsRoute
  '/constituency': typeof ConstituencyRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/news': typeof NewsRoute
  '/schemes': typeof SchemesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/complaints'
    | '/constituency'
    | '/contact'
    | '/development'
    | '/news'
    | '/schemes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/complaints'
    | '/constituency'
    | '/contact'
    | '/development'
    | '/news'
    | '/schemes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/complaints'
    | '/constituency'
    | '/contact'
    | '/development'
    | '/news'
    | '/schemes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ConstituencyRoute: typeof ConstituencyRoute
  ContactRoute: typeof ContactRoute
  DevelopmentRoute: typeof DevelopmentRoute
  NewsRoute: typeof NewsRoute
  SchemesRoute: typeof SchemesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constituency': {
      id: '/constituency'
      path: '/constituency'
      fullPath: '/constituency'
      preLoaderRoute: typeof ConstituencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComplaintsRoute: ComplaintsRoute,
  ConstituencyRoute: ConstituencyRoute,
  ContactRoute: ContactRoute,
  DevelopmentRoute: DevelopmentRoute,
  NewsRoute: NewsRoute,
  SchemesRoute: SchemesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
